---
- name: Configure roles on web server
  hosts: all
  vars:
    web_document_root: "/var/www/teamdigitale.governo.it"
    # NGINX role, see https://galaxy.ansible.com/geerlingguy/nginx/
    nginx_remove_default_vhost: true
    nginx_sendfile: "on"
    nginx_tcp_nopush: "on"
    nginx_tcp_nodelay: "on"
    nginx_server_tokens: "off"
    nginx_ppa_use: true
    nginx_ppa_version: "stable"
    nginx_vhosts:
      - listen: "80"
        server_name: "teamdigitale.governo.it"
        root: "{{ web_document_root }}"
        index: "index.html"
        extra_parameters: |
          expires $expires;

  tasks:
    - name: "NGINX cache expire config map"
      copy:
        content: |
          # Expires map
          map $sent_http_content_type $expires {
              default                    off;
              text/html                  epoch;
              text/css                   max;
              application/javascript     max;
              ~image/                    max;
          }
        dest: /etc/nginx/conf.d/expires_map.conf

    - name: "Document root directory"
      file:
        path: "{{ web_document_root }}"
        owner: root
        group: root
        state: directory
        mode: 0755

  roles:
    - { role: geerlingguy.nginx }
